sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Guozhaonan123
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEn31WughHkjjxLu9jz
    access-key-secret: 0K18g5gNDpSgK7Krfy2ZAPKm4vaNJU
    bucket-name: gzn-web
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxb248abeca0f52929
    secret: daf96850189a2d5d47e9f2a3eb1d72c6
  shop:
    address: 辽宁省大连市经济技术开发区图强路136-1、2、3号一层
  baidu:
    ak: osg53mDFtuTZ6dKFCXrkSN7BorDhrnS1